### ISSUE TITLE
Use of objects in LUMOS

### ISSUE THREAD

**Issue by Alfie58** [Frudawski/LUMOS#8]
I need to simulate lighting in 5 different room designs. In each room I need to locate, in turn, 12 different pre-designed objects. Each object is composed of 3 stacked boxes (of different dimensions). In designing the objects I assume I can use the grouping option in the GUI. I am not entirely clear, however, if there is a way of storing these objects so that I can use them repeatedly in each different room design. Any tips useful before I embark on this.

**Comment by Frudawski** [comment]
1. Create the room layout:
You can than either duplicate your room layout 11 times in the room tab (right-click in the list), that way  all objects are simulated in one go - result structure might be a bit messy though, or you duplicate your project file 11 times and start your 12 simulations separately. If the simulations just take a few minutes, I would go with separate files for sake of better overview.

2. Import / export objects:
You can group your stacked boxes into one object and export it for use in other projects. That way, you need to create each objects just once and can import it in any other project. Use the floppy disc and folder symbol in the menu bar when the object tab is selected.

**Comment by Alfie58** [comment]
Ah. I've figure out how to group objects. Having selected the 'group object' gui it is possible to select multiple objects and save them as one new object with a new name.  Just learning as I go in the absence of a users manual.

**Comment by Alfie58** [comment]
Next issue is saving the grouped object and then loading it. If I select the grouped object and then select 'save object' I get:-
Unrecognized function or variable 'savefile'.

Error in spec_simulation>uitoggletool21_ClickedCallback (line 11061)
file = savefile('object','obt');

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in spec_simulation (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)spec_simulation('uitoggletool21_ClickedCallback',hObject,eventdata,guidata(hObject))
 
Error while evaluating PushTool ClickedCallback.

Unrecognized function or variable 'savefile'.

Error in spec_simulation>uitoggletool21_ClickedCallback (line 11061)
file = savefile('object','obt');

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in spec_simulation (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)spec_simulation('uitoggletool21_ClickedCallback',hObject,eventdata,guidata(hObject))
 
Error while evaluating PushTool ClickedCallback.

Unrecognized function or variable 'loadfile'.

Error in spec_simulation>uitoggletool22_ClickedCallback (line 11071)
file = loadfile('object','obt');

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in spec_simulation (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)spec_simulation('uitoggletool22_ClickedCallback',hObject,eventdata,guidata(hObject))
 
Error while evaluating PushTool ClickedCallback.

>>

**Comment by Frudawski** [comment]
Indeed, the function savefile.m as well as loadifle.m was missing from the repository. I added both files and released a new version 1.11 which fixes the problem.

Unfortunately, I currently have no time to prepare a proper manual for LUMOS, but I will try to prepare a how-to video at the end of the month which demonstrates the workflow and functionality of the program.
